# PostgreSQL 10

default: &default
  adapter: postgresql
  host: localhost
  username: lucas
  password: password

production:
  <<: *default
  database: exercise

development:
  <<: *default
  database: exercise_dev

test:
  <<: *default
  database: exercise_test

